name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        git clone https://github.com/olikraus/u8g2.git /tmp/u8g2
        git clone https://github.com/Makuna/NeoPixelBus.git /tmp/NeoPixelBus
        git clone https://github.com/bblanchon/ArduinoJson.git /tmp/ArduinoJson

    - name: Control Board CI
      run: platformio ci src/main.cpp --lib="." --lib="/tmp/u8g2/*" --lib="/tmp/ArduinoJson/*" --board=esp32dev --project-option="build_flags= -DCORE_DEBUG_LEVEL=0 -DCONTROL_BOARD=1 -DLED_BOARD=0"

#    - name: LED Board CI
#      run: platformio ci src/main.cpp --lib="." --lib="/tmp/NeoPixelBus/*" --board=esp32dev --project-option="build_flags= -DCORE_DEBUG_LEVEL=0 -DCONTROL_BOARD=0 -DLED_BOARD=1"