name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        git clone https://github.com/olikraus/u8g2.git /tmp/u8g2
        git clone https://github.com/Makuna/NeoPixelBus.git /tmp/NeoPixelBus
        git clone https://github.com/bblanchon/ArduinoJson.git /tmp/ArduinoJson
        git clone https://github.com/gilmaimon/ArduinoWebsockets.git /tmp/ws

    - name: Control Board CI
      run: platformio run -e controlBoard

    - name: LED Board CI
      run: platformio run -e ledBoard